const mutations = {
  SET_PRODUCTS_TO_STATE: "SET_PRODUCTS_TO_STATE",
  TO_CART: "TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  DECREMENT: "DECREMENT",
  INCREMENT: "INCREMENT",
  IS_LOGGED_IN: "IS_LOGGED_IN",
  LOGIN_LOADER: "LOGIN_LOADER",
  SIGNUP_LOADER: "SIGNUP_LOADER",
  RESET_PASSWORD_LOADER: "RESET_PASSWORD_LOADER",
  SHOW_NOTIFY: "SHOW_NOTIFY",
  USER: "USER"
};

export default mutations;
